# nginx configuration file
events { worker_connections 1024; }

http{
    # Define an upstream cluster for the backend application
    upstream backend_cluster {
        server app: 8000;
    }

    # Define a server block to handle incoming requests
    server {
        listen 80; # Listen on port 80 for HTTP requests
        
        # Define a location block for the /process endpoint
        location /process {
            proxy_pass http://backend_cluster; # Forward requests to the backend cluster
            proxy_set_header Host $host; # Set the Host header to the original host
            proxy_set_header X-Real-IP $remote_addr; # Set the X-Real-IP header to the client's IP address
        }

        # Define a location block for the /metrics endpoint
        location /metrics {
            proxy_pass http://backend_cluster; # Forward requests to the backend cluster
        }
    }
}