# Dockerfile for FastAPI application with Prometheus metrics
FROM python:3.10-slim 

# Set the working directory in the container
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastapi unvicorn prometheus_client

# Copy the application code to the container
COPY main.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]